MiniProject228/Controllers/OnlineTestController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace MiniProject228.Controllers
{
    public class OnlineTestController : Controller
    {
        // GET: OnlineTest
        public ActionResult Index()
        {
            return View("Index", OnlineTestRepo.ByBiodata());
        }
        public ActionResult List(int id)
        {
            Session["Biodata"] = id;
            return PartialView("_List", OnlineTestRepo.All(id));
        }

        public ActionResult Addr(int id)
        {
            return PartialView("_Addr", OnlineTestRepo.ByAddr(id));
        }
        public ActionResult TestType(int Id)
        {
            List<TestDetailViewModel> model = OnlineTestRepo.ById(Id);
            Session["Tipe"] = Id;
            return PartialView("_TestType", model);
        }

        public ActionResult SelectTest(int id)
        {
            TestDetailViewModel type = TestTypeRepo.ByTestType(id);
            return PartialView("_SelectTest", type);
        }

        [HttpPost]
        public ActionResult Simpan(TestViewModel model)
        {
            model.biodata_id = int.Parse(Session["Biodata"].ToString());
            ResultOrder result = OnlineTestRepo.Post(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    reference = result.Reference
                }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Create()
        {

            ViewBag.TestTypeList = new SelectList(TestTypeRepo.All(), "Id", "name");
            return PartialView("_Create", new TestViewModel());
        }

        [HttpPost]
        public ActionResult Create(TestViewModel model)
        {
            int test = int.Parse(Session["Biodata"].ToString());
            ResponseResult result = OnlineTestRepo.Update(model, test);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CreateType()
        {
            ViewBag.TypeList = new SelectList(TestTypeRepo.All(), "Id", "Name");
            return PartialView("_CreateType", new TestDetailViewModel());
        }

        public ActionResult TambahTipe()
        {
            ViewBag.TypeList = new SelectList(TestTypeRepo.All(), "Id", "Name");
            TestDetailViewModel model = new TestDetailViewModel();
            return PartialView("_TambahTipe", model);
        }

        [HttpPost]
        public ActionResult TambahTipe(TestDetailViewModel model)
        {
            model.online_test_id = long.Parse(Session["Tipe"].ToString());
            ResponseResult result = TestTypeRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CreateType(TestDetailViewModel model)
        {
            int test = int.Parse(Session["Biodata"].ToString());
            ResponseResult result = TestTypeRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(int id)
        {
            // id => Keahlian Id
            TestViewModel model = OnlineTestRepo.byId(id);
            ViewBag.TestTypeList = new SelectList(TestTypeRepo.All(), "Id", "Name");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(TestViewModel model)
        {
            int test = int.Parse(Session["Biodata"].ToString());
            ResponseResult result = OnlineTestRepo.Update(model, test);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int id)
        {
            // id => Category Id
            return PartialView("_Delete", OnlineTestRepo.byId(id));
        }

        [HttpPost]
        public ActionResult Delete(TestViewModel model)
        {
            ResponseResult result = OnlineTestRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteTes(int id)
        {
            // id => Category Id
            return PartialView("_DeleteTes", TestTypeRepo.ByDel(id));
        }

        [HttpPost]
        public ActionResult DeleteTes(TestDetailViewModel model)
        {
            ResponseResult result = TestTypeRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

MiniProject228/Views/OnlineTest/Index.cshtml
@model IEnumerable<ViewModel.BiodataViewModel>

@{
    ViewBag.Title = "Index";
}
<style>
    .nav-item {
        border: groove;
        border-bottom: none;
    }

    .nav-item-end {
        border: groove;
        border-bottom: groove;
    }

    .modal {
        overflow-y: auto;
    }
</style>

<table class="table">
    <tr>
        <th>
            Nama
        </th>
        <th>
            #
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.fullname)
            </td>
            <td>
                <button type="button" class="btn btn-success btn-select" data-id="@item.id" data-dismiss="modal" title="Select">Detil Pelamar</button>
            </td>

        </tr>

    }

</table>

<div class="modal fade" id="exampleList" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title modal-title-list">Detil Pelamar</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-3">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Profil</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Biodata</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Pengalaman Kerja</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Pendidikan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Pelatihan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Sertifikasi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Sumber Lowongan Kerja</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Organisasi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Keluarga</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="#">Keahlian</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Lain-Lain</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Dokumen</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Catatan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="#" id="select-akun">Aktivasi Akun</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Lihat Tes</a>
                                </li>
                                <li class="nav-item-end">
                                    <a class="nav-link" href="#">Hasil Tes</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-9" id="list-test" style="max-width:2500px;">

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>





@section Scripts{
    <script type="text/javascript">

            var kl;
            $(".btn-select").click(function () {
                kl = $(this).attr("data-id");
            $.ajax({
                type: 'get',
                success: function (result) {
                    $("#exampleList").modal("show");
                }
            });
        });

            $("#select-akun").click(function () {
            $.ajax({
                url: '@Url.Action("List","OnlineTest")',
                type: 'get',
                data: { id: kl },
                success: function (result) {

                    $("#list-test").html(result);
                    GetAddr();
                }
            });
            });

        function GetList() {
                $.ajax({
                url: '@Url.Action("List","OnlineTest")',
                type: 'get',
                data: { id: kl },
                success: function (result) {
                    $("#list-test").html(result);
                    GetAddr();
                }
         });
        }

        $(".close").on("click", function () {
            window.location.reload();
        });

        function GetAddr() {
            $.ajax({
                url: '@Url.Action("Addr","OnlineTest")',
                type: 'get',
                data: { id: kl },
                success: function (result) {
                    $("#data-addrbook").html(result);
                }
            });
        }
    </script>
}

MiniProject228/Views/OnlineTest/_Addr.cshtml
@model ViewModel.TestViewModel

<tr>
        <td>
            <b>Username:</b>
        </td>
        <td>
            @Html.DisplayFor(model => model.abuid) <b> - Tidak Aktif</b>
        </td>
    </tr>
    <tr>
        <td>
            <b>Password:</b>
        </td>
        <td>
            @Html.DisplayFor(model => model.abpwd)
        </td>
    </tr>

MiniProject228/Views/OnlineTest/_Create.cshtml
@model ViewModel.TestViewModel

@Html.AntiForgeryToken()
<div class="form-group">
    <div class="row">
        <div class="col-sm-4">
            <label>Tgl. Tes*</label>
            <input type="date" class="form-control test_date" id="test_date" name="test_date" value="">
            <span class="text-danger" id="test_error"></span>
        </div>
        <div class="col-sm-4">
            <label>Tgl. Berakhir Tes*</label>
            <input type="date" class="form-control expired_test" id="expired_test" name="expired_test">
            <span class="text-danger" id="ex_error"></span>
            <small class="form-text text-muted Validation" id="Validation" style="display:none; color:red;">Tanggal berakhir tes tidak boleh kurang dari tanggal tes mulai</small>
        </div>
        <div class="col-sm-4">
            <label>Akses User*</label>
            <select class="form-control" id="user_access" name="user_access">
                <option value="INSIDE">INSIDE</option>
                <option value="OUTSIDE">OUTSIDE</option>
            </select>
            <span class="text-danger" id="user_error"></span>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-10">
        <div class="col-md-offset-11 col-md-7" style="margin-right:3px;">
            <button id="btn-tambah" class="btn btn-primary">Tambah Test</button>
        </div>
    </div>
</div>
<div>
    <div class="panel-body">
        <table class="table table-bordered table-striped" id="test-table">
            <thead>
                <tr>
                    <th style="width: 40%">Jenis Tes</th>
                    <th style="width: 20%">#</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-lg-10">
            <div class="col-md-offset-9 col-md-7">
                <button class="btn btn-warning" id="batal">Batal</button>
                <button value="Simpan" id="btn-save" class="btn btn-primary">Simpan & kirim</button>
                </div>
            </div>
            </div>

            <div class="modal fade" id="exampleTambah" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-primary header-modal-sm">
                            <h4 class="modal-title modal-title-tambah">Modal title</h4>
                        </div>
                        <div class="modal-body modal-tambah">
                            <p>One fine body&hellip;</p>
                        </div>
                    </div>
                </div>
            </div>



            <script type="text/javascript">
        //$(document).ready(function () {
        //    GetList();
        //});

        $("#expired_test").change(function () {
            var exdate = $("#expired_test").val();
            var strdate = $("#test_date").val();
            if (exdate < strdate) {
                $("#Validation").show();
            }
            else {
                $("#Validation").hide();
            }
        });

        $("#test_date").change(function () {
            var exdate = $("#expired_test").val();
            var strdate = $("#test_date").val();
            if (exdate < strdate && exdate != "") {
                $("#Validation").show();
            }
            else {
                $("#Validation").hide();
            }
        });

    $("#btn-tambah").click(function () {
            $.ajax({
                url: '@Url.Action("CreateType", "OnlineTest")',
                type: 'get',
                success: function (result) {
                    $(".modal-title-tambah").html("Tambah Tes");
                    $(".modal-tambah").html(result);
                    $("#exampleTambah").modal("show");
                }
            });
    });

        $("#batal").on("click", function () {
            $("#modalExam").modal("hide");
        });

                function Remove(obj) {
            var tr = $(obj).closest('tr');
                tr.remove();
        }

        var data = {};
            $("#btn-save").click(function () {
            var test = $("#test_date").val();
            var ex = $("#expired_test").val();
            var user = $("#user_access").val();
            var details = [];
            $("#test-table tbody").find("tr").each(function () {
                var Id = $(this).find("input[name=id]").val();
                detail = {
                    test_type_id: Id,
                };
                details.push(detail);
            });

            data = {
                test_date: $("#test_date").val(),
                expired_test: $("#expired_test").val(),
                user_access: $("#user_access").val(),
                detail: details
            }
        $.ajax({
            url: '@Url.Action("Simpan", "OnlineTest")',
            type: 'post',
            data: { model: data },
            success: function (result) {
                $("#test_error").html("");
                $("#ex_error").html("");
                $("#user_error").html("");
                if (result.success) {
                    $("#modalExam").modal("hide");
                    GetList();
                }
               else if (test == "" && ex == "" && user == "") {
                    $("#test_error").html("tanggal test tidak boleh kosong!");
                    $("#ex_error").html("tanggal berakhir test tidak boleh kosong");
                    $("#user_error").html("user access tidak boleh kosong");
                }
                else {
                    alert("Error:\n" + result.message);
                }
            }
        });
    });

            </script>

MiniProject228/Views/OnlineTest/_CreateType.cshtml
@model ViewModel.TestDetailViewModel

@using (Html.BeginForm("CreateType", "OnlineTest", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10" style="margin-left:5%;">
                <label>Jenis Tes</label>
                @Html.DropDownListFor(model => model.test_type_id,
  (IEnumerable<SelectListItem>)ViewBag.TypeList, "-pilih-", new
  { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.test_type_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-warning btn-batal" title="Batal">
                    Batal
                </button>
                <button type="submit" class="btn btn-success btn-select" value="" title="Select">
                    Tambah
                </button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#exampleTambah").modal("hide");
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });

    $(".btn-select").click(function () {
        $.ajax({
            url: '@Url.Action("SelectTest","OnlineTest")',
            type: 'get',
            data: { id: $(this).attr("value") },
            success: function (result) {
                $("#test-table tbody").append(result);
                $("#exampleTambah").modal("hide");
                //GetList();
            }
        });
    });

    $("#test_type_id").change(function () {
        var test = $("#test_type_id").val();
        $(".btn-select").attr("value", test);
    })

     $(".btn-batal").on("click", function () {
        $("#exampleTambah").modal("hide");
    });
</script>

MiniProject228/Views/OnlineTest/_Delete.cshtml
@model ViewModel.TestViewModel

<style>
    .glyphicon-trash {
        font-size: 80px;
    }
</style>
<div class="row">
    <div class="panel-heading">
        <div class="col-md-3" style="margin-left:8%; margin-top:2%;">
            <span class="glyphicon glyphicon-trash"></span>
        </div>
        <div class="col-md-8" style="color:red">
            <span>Apakah anda yakin ingin menghapus Tes</span>
            <br />
            @Html.DisplayFor(Model => Model.period_code)<a style="color:red"> ?</a>
        </div>
    </div>
</div>
<div>
    <hr />
    @using (Html.BeginForm("Delete", "OnlineTest", FormMethod.Post,
            new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                <div class="col-md-offset-8 col-md-10">
                    <input type="button" value="batal" class="btn btn-warning btn-batal" />
                    <input type="submit" value="Ya" class="btn btn-danger" />
                </div>
            </div>
        </div>
    }

</div>

<script type="text/javascript">
            $("#form-delete").submit(function () {
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            $("#exampleCreate").modal("hide");
                            GetList();
                        } else {
                            alert("error! " + result.message);
                        }
                    }
                });
                return false;
            });
            $(".btn-batal").on("click",function () {
            $("#modalExam").modal("hide");
    });
</script>

MiniProject228/Views/OnlineTest/_DeleteTes.cshtml
@model ViewModel.TestDetailViewModel

    <div class="panel-heading">
        <div class="col-md-3" style="color:red; margin-left:20%; margin-top:2%; font-size: 80px;">
            <span class="glyphicon glyphicon-trash"></span>
        </div>
        <br/>
        <div class="col-md-12" style="color:red; margin-top:2%; margin-left:10%;">
            <span>Apakah anda yakin ingin menghapus Tipe Tes?</span>
            <br/>
        </div>
    </div>
<div>
    @using (Html.BeginForm("DeleteTes", "OnlineTest", FormMethod.Post,
            new { id = "form-delete", name = "form-delete" }))
    {
        <div class="form-horizontal">
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                <div class="col-md-offset-3 col-md-10" style="margin-top:5%;">
                    <input type="button" value="batal" class="btn btn-warning btn-batal" />
                    <input type="submit" value="Ya" class="btn btn-danger btn-ya" />
                </div>
            </div>
        </div>
    }

</div>

<script type="text/javascript">
    $("#form-delete").submit(function () {
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            $("#exampleTambahBaru").modal("hide");
                            GetList();
                            GetTest();
                        } else {
                            alert("error! " + result.message);
                        }
                    }
                });
                return false;
            });
            $(".btn-batal").on("click",function () {
            $("#exampleTambahBaru").modal("hide");
    });
</script>

MiniProject228/Views/OnlineTest/_List.cshtml
@model IEnumerable<ViewModel.TestViewModel>

<style>
    .row-garis {
        border-bottom: 3px solid #337ab7;
    }
</style>

<div class="panel-heading">
    <div class="row row-garis">
        <div class="col-md-6">
            <b>Aktivasi Akun Tes Online</b>
        </div>
        <div class="col-md-offset-10" style="margin-bottom:2%;">
            <button id="btn-create-new" class="btn btn-primary" aria-hidden="true">Aktifkan</button>
        </div>
    </div>
</div>

<div id="data-addrbook">
</div>
<br />

<table class="table table-striped">
    <tr>
        <th>
            Kode Periode
        </th>
        <th>
            Periode
        </th>
        <th>
            Tgl Tes
        </th>
        <th>
            Tgl Berakhir Tes
        </th>
        <th>
            Akses
        </th>
        <th>
            Status
        </th>
        <th>
            #
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.period_code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.period)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.test_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.expired_test)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.user_access)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>

                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a class="btn-tampilkan" data-id="@item.id">Tampilkan Pilihan Test</a></li>
                        <li><a class="btn-delete" data-id="@item.id">Hapus</a></li>
                    </ul>
                </div>
            </td>

        </tr>
    }

</table>

<div class="modal fade" id="modalExam" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header header-modal-sm"> <h4 class="modal-title modal-title-exam" style="color:white;">Modal title</h4>
            </div>
            <div class="modal-body modal-create">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    

        $("#btn-create-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "OnlineTest")',
                type: 'get',
                data: { id: $(this).attr("data-id")},
                success: function (result) {
                    $(".header-modal-sm").css("background-color", "#337ab7");
                    $(".modal-title-exam").html("Aktivasi Akun Tes");
                    $(".modal-create").html(result);
                    $("#modalExam").modal("show");
                }
            });
        });
    var idTipe;
    $(".btn-tampilkan").click(function () {
        idTipe = $(this).attr("data-id");
        $.ajax({
            url: '@Url.Action("TestType", "OnlineTest")',
            type: 'get',
            data: { id: idTipe},
            success: function (result) {
                $(".header-modal-sm").css("background-color", "#337ab7");
                $(".modal-title-exam").html("Pilihan Tes");
                $(".modal-create").html(result);
                $("#modalExam").modal("show");
            }
        });
    });

    function GetTest() {
                $.ajax({
            url: '@Url.Action("TestType", "OnlineTest")',
            type: 'get',
            data: { id: idTipe},
            success: function (result) {
                $(".header-modal-sm").css("background-color", "#337ab7");
                $(".modal-title-exam").html("Pilihan Tes");
                $(".modal-create").html(result);
                $("#modalExam").modal("show");
                }
         });
        }

     $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "OnlineTest")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".header-modal-sm").css("background-color", "red");
                $(".modal-title-exam").html("Hapus Tes?");
                $(".modal-create").html(result);
                $("#modalExam").modal("show");
            }
        });
    });
</script>

MiniProject228/Views/OnlineTest/_TambahTipe.cshtml
@model ViewModel.TestDetailViewModel

@using (Html.BeginForm("TambahTipe", "OnlineTest", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10" style="margin-left:5%;">
                <label>Jenis Tes</label>
                @Html.DropDownListFor(model => model.test_type_id,
  (IEnumerable<SelectListItem>)ViewBag.TypeList, "-pilih-", new
  { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.test_type_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-warning btn-batal" title="Batal">
                    Batal
                </button>
                <button type="submit" class="btn btn-success btn-select" value="" title="Select">
                    Tambah
                </button>
            </div>
        </div>
    </div>
}

    <script type="text/javascript">

        $(".btn-select").click(function () {
            //alert($("#test_type_id").val());
            $.ajax({
                url: '@Url.Action("TambahTipe","OnlineTest")',
                type: 'post',
                data: {test_type_id:$("#test_type_id").val()},
            success: function (result) {
                if (result.success) {
                    $("#exampleTambahBaru").modal("hide");
                    GetList();
                    GetTest();
                } else {
                    alert("error! " + result.message);
                }
            }     
        });
        return false;
        });

         $(".btn-batal").on("click", function () {
        $("#exampleTambahBaru").modal("hide");
    });

    </script>