MiniProject228/Controllers/EducationLevelController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace MiniProject228.Controllers
{
    public class EducationLevelController : Controller
    {
        // GET: EducationLevel
        public ActionResult Index()
        {
            return View();
        }
    public ActionResult List()
        {
            return PartialView("_List", EducationLevelRepo.All());
        }
        public ActionResult Create()
        {
            return PartialView("_Create", new EducationLevelViewModel());
        }

        [HttpPost]
        public ActionResult Create(EducationLevelViewModel model)
        {
            ResponseResult result = EducationLevelRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(int id)
        {
            // id => Category Id
            return PartialView("_Edit", EducationLevelRepo.byId(id));
        }

        [HttpPost]
        public ActionResult Edit(EducationLevelViewModel model)
        {
            ResponseResult result = EducationLevelRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int id)
        {
            // id => Category Id
            return PartialView("_Delete", EducationLevelRepo.byId(id));
        }

        [HttpPost]
        public ActionResult Delete(EducationLevelViewModel model)
        {
            ResponseResult result = EducationLevelRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

MiniProject228/Views/EducationLevel/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <input id="btn-create-new" type="button" class="btn btn-default btn-lg" value="Create New" />
    </div>
    <div class="panel-body">
    </div>

    <!--Table-->
    <div id="data-list">
        Loading...
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "EducationLevel")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        }

        $("#btn-create-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "EducationLevel")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Create New");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });
    </script>
}

MiniProject228/Views/EducationLevel/_Create.cshtml
@model ViewModel.EducationLevelViewModel

@using (Html.BeginForm("Create", "EducationLevel", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EducationLevelViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Save successful! Nama: " + result.entity.Name);
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });
</script>

MiniProject228/Views/EducationLevel/_List.cshtml
@model IEnumerable<ViewModel.EducationLevelViewModel>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-warning btn-edit" data-id="@item.id"
                            title="Edit">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-warning btn-delete" data-id="@item.id"
                            title="Delete">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </td>

        </tr>

    }

</table>

<script type="text/javascript">
    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "EducationLevel")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".modal-title").html("Edit");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });
     $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "EducationLevel")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".modal-title").html("Delete");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });
</script>