MiniProject228/Controllers/KeahlianController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace MiniProject228.Controllers
{
    public class KeahlianController : Controller
    {
        // GET: Keahlian
        public ActionResult Index()
        {
            return View("Index", KeahlianRepo.ByBiodata());
        }
        public ActionResult List(int id)
        {
            Session["Biodata"] = id;
            return PartialView("_List", KeahlianRepo.All(id));
        }
        public ActionResult Create()
        {

            ViewBag.SkillLevelList = new SelectList(SkillLevelRepo.All(), "Id", "name");
            return PartialView("_Create", new KeahlianViewModel());
        }

        [HttpPost]
        public ActionResult Create(KeahlianViewModel model)
        {
            int bio = int.Parse(Session["Biodata"].ToString());
            ResponseResult result = KeahlianRepo.Update(model, bio);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(int id)
        {
            // id => Keahlian Id
            KeahlianViewModel model = KeahlianRepo.byId(id);
            ViewBag.SkillLevelList = new SelectList(SkillLevelRepo.All(), "Id", "Name");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(KeahlianViewModel model)
        {
            int bio = int.Parse(Session["Biodata"].ToString());
            ResponseResult result = KeahlianRepo.Update(model,bio);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int id)
        {
            // id => Category Id
            return PartialView("_Delete", KeahlianRepo.byId(id));
        }

        [HttpPost]
        public ActionResult Delete(KeahlianViewModel model)
        {
            ResponseResult result = KeahlianRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

MiniProject228/Views/Keahlian/Index.cshtml
@model IEnumerable<ViewModel.BiodataViewModel>

@{
    ViewBag.Title = "Index";
}
<style>
    .nav-item {
        border: 2px solid #337ab7;
        border-bottom: none;
    }

    .nav-item-end {
        border: 2px solid #337ab7;
        border-bottom: 2px solid #337ab7;
    }

    .modal {
        overflow-y: auto;
    }
</style>

<table class="table">
    <tr>
        <th>
            Nama
        </th>
        <th>
            #
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.fullname)
            </td>
            <td>
                <button type="button" class="btn btn-success btn-select" data-id="@item.id" data-dismiss="modal" title="Select">Detil Pelamar</button>
            </td>

        </tr>

    }

</table>

<div class="modal fade" id="exampleList" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title modal-title-list" id="titleIndex">Detil Pelamar</h4>
            </div>
            <div class="modal-body modal-body-list" id="bodyIndex">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Profil</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Biodata</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Pengalaman Kerja</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Pendidikan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Pelatihan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Sertifikasi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Sumber Lowongan Kerja</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Organisasi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Keluarga</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="#" id="select-keahlian">Keahlian</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Lain-Lain</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Dokumen</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Catatan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Aktivasi Akun</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Lihat Tes</a>
                                </li>
                                <li class="nav-item-end">
                                    <a class="nav-link" href="#">Hasil Tes</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-8" id="list-keahlian">

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script type="text/javascript">

            var kl;
            $(".btn-select").click(function () {
                kl = $(this).attr("data-id");
            $.ajax({
                type: 'get',
                success: function (result) {
                    $("#exampleList").modal("show");
                }
            });
        });

            $("#select-keahlian").click(function () {
            $.ajax({
                url: '@Url.Action("List","Keahlian")',
                type: 'get',
                data: { id: kl },
                success: function (result) {

                    $("#list-keahlian").html(result);
                }
            });
            });

        function GetList() {
                $.ajax({
                url: '@Url.Action("List","Keahlian")',
                type: 'get',
                data: { id: kl },
                success: function (result) {
                $("#list-keahlian").html(result);
                }
         });
        }

        $(".close").on("click", function () {
            window.location.reload();
    }); 
    </script>
}

MiniProject228/Views/Keahlian/Tombol.cshtml
@{
    ViewBag.Title = "Tombol";
}

<h2>Tombol</h2>

MiniProject228/Views/Keahlian/_Create.cshtml
@model ViewModel.KeahlianViewModel

@using (Html.BeginForm("Create", "Keahlian", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <style>
        #responsibility,#notes{
            max-width:1000px;
        }
    </style>

    <div class="form-group">
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="col-sm-5" style="margin-left:5%;">
                <label>Nama Keahlian</label>
                @Html.EditorFor(model => model.skill_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skill_name, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-5" style="margin-left:5%;">
                <label>Level Keahlian*</label>
                @Html.DropDownListFor(model => model.skill_level_id,
                    (IEnumerable<SelectListItem>)ViewBag.SkillLevelList, "-Pilih-", new
                    { @class = "form-control", Required="true", @oninvalid="setCustomValidity('Level keahlian Harus Diisi')", @oninput = "setCustomValidity('')" })
                    @Html.ValidationMessageFor(model => model.skill_level_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" style="margin-left:5%;">
                <label>Catatan</label><br />
                @Html.TextAreaFor(model => model.notes,5,68, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10">
                <div class="col-md-offset-8 col-md-10">
                    <input type="button" value="batal" class="btn btn-warning btn-batal" />
                    <input type="submit" value="Simpan" class="btn btn-primary" />
                </div>
            </div>
        </div>

    </div>
}

<div />

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#exampleCreate").modal("hide");
                    GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });

     $(".btn-batal").on("click",function () {
        $("#exampleCreate").modal("hide");
    }); 

</script>

MiniProject228/Views/Keahlian/_Delete.cshtml
@model ViewModel.KeahlianViewModel

<style>
    .glyphicon-trash{
        font-size:80px;
    }
</style>
    <div class="row">
        <div class="panel-heading">
            <div class="col-md-3" style="margin-left:8%; margin-top:2%;">
                <span class="glyphicon glyphicon-trash"></span>
            </div>
            <div class="col-md-8" style="color:red">
                <span>Apakah anda yakin ingin menghapus keahlian</span>
                <br />
                @Html.DisplayFor(Model => Model.skill_name)<a style="color:red"> ?</a>
            </div>
        </div>
     </div>
        <div>
            <hr />
            @using (Html.BeginForm("Delete", "Keahlian", FormMethod.Post,
                    new { id = "form-delete", name = "form-delete" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        <div class="col-md-offset-8 col-md-10">
                            <input type="button" value="batal" class="btn btn-warning btn-batal" />
                            <input type="submit" value="Ya" class="btn btn-danger" />
                        </div>
                    </div>
                </div>
            }

        </div>

        <script type="text/javascript">
            $("#form-delete").submit(function () {
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            $("#exampleCreate").modal("hide");
                            GetList();
                        } else {
                            alert("error! " + result.message);
                        }
                    }
                });
                return false;
            });
            $(".btn-batal").on("click",function () {
            $("#exampleCreate").modal("hide");
    }); 
        </script>

MiniProject228/Views/Keahlian/_Edit.cshtml
@model ViewModel.KeahlianViewModel


@using (Html.BeginForm("Edit", "Keahlian", FormMethod.Post,
    new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()
    <style>
        #responsibility, #notes {
            max-width: 1000px;
        }
    </style>

    <div class="form-group">
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="col-sm-5" style="margin-left:5%;">
                <label>Nama Keahlian</label>
                @Html.EditorFor(model => model.skill_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skill_name, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-5" style="margin-left:5%;">
                <label>Level Keahlian*</label>
                @Html.DropDownListFor(model => model.skill_level_id,
                    (IEnumerable<SelectListItem>)ViewBag.SkillLevelList, "-Pilih-", new
                    { @class = "form-control", Required = "true", @oninvalid = "setCustomValidity('Level keahlian Harus Diisi')", @oninput = "setCustomValidity('')" })
                @Html.ValidationMessageFor(model => model.skill_level_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" style="margin-left:5%;">
                <label>Catatan</label><br />
                @Html.TextAreaFor(model => model.notes, 5, 68, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-lg-11">
                <div class="form-group col-lg-10">
                    <div class="col-md-offset-8 col-md-9">
                        <input type="button" value="batal" class="btn btn-danger btn-batal" />
                        <input type="submit" value="Simpan" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#exampleCreate").modal("hide");
                    GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });
    $(".btn-batal").on("click", function () {
        $("#exampleCreate").modal("hide");
    });

</script>

MiniProject228/Views/Keahlian/_List.cshtml
@model IEnumerable<ViewModel.KeahlianViewModel>

<style>
    .garis {
        border-bottom: 3px solid black;
        border-top: 2px solid black;
    }
</style>

<!-- Default panel contents -->
<div class="panel-heading">
    <b>Keahlian   </b> <span id="btn-create-new" class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
</div>
<table class="table table-striped">
    <tr class="garis">
        <th>
            Nama Keahlian
        </th>
        <th>
            Level Keahlian
        </th>
        <th>
            #
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.skill_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.level_keahlian)
            </td>
            <td>

                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a class="btn-edit" data-id="@item.Id">Ubah</a></li>
                        <li><a class="btn-delete" data-id="@item.Id">Hapus</a></li>
                    </ul>
                </div>
            </td>

        </tr>
    }

</table>

<div class="modal fade" id="exampleCreate" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary header-modal-sm">
                <h4 class="modal-title modal-title-create">Modal title</h4>
            </div>
            <div class="modal-body modal-create">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">


        $("#btn-create-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Keahlian")',
                type: 'get',
                data: { id: $(this).attr("data-id")},
                success: function (result) {
                    $(".header-modal-sm").css("background-color", "#337ab7");
                    $(".modal-title-create").html("Tambah Keahlian");
                    $(".modal-create").html(result);
                    $("#exampleCreate").modal("show");
                }
            });
        });

    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Keahlian")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".header-modal-sm").css("background-color", "#337ab7");
                $(".modal-title-create").html("Ubah Keahlian");
                $(".modal-create").html(result);
                $("#exampleCreate").modal("show");
            }
        });
    });
     $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Keahlian")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".header-modal-sm").css("background-color", "red");
                $(".modal-title-create").html("Hapus Keahlian?");
                $(".modal-create").html(result);
                $("#exampleCreate").modal("show");
            }
        });
    });
</script>