MiniProject228/Controllers/TimesheetSubmissionController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace MiniProject228.Controllers
{
    public class TimesheetSubmissionController : Controller
    {
        // GET: TimesheetSubmission
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            ViewBag.getYear = SubmissionRepo.ListYear();
            ViewBag.getMonth = SubmissionRepo.ListMonth();

            return PartialView("_List");

        }

        public ActionResult EmailCC(List<long> id, List<long> idClient, string year, string month)
        {
            Session["Id"] = id;
            Session["IdClient"] = idClient;
            ViewBag.getYear = SubmissionRepo.ListYear();
            ViewBag.getMonth = SubmissionRepo.ListMonth();

            return PartialView("_EmailCC");
        }

            public ActionResult listTimesheetView(string month, string year)
        {
            ViewBag.getYear = SubmissionRepo.ListYear();
            ViewBag.getMonth = SubmissionRepo.ListMonth();

            List<TimesheetViewModal> listTimesheet = new List<TimesheetViewModal>();
            if ((year != null || year != "") && (month != null || month != ""))
            {
                listTimesheet = SubmissionRepo.getDataTimesheet(year, month);
            }

            ViewBag.idSend = listTimesheet.Select(a => a.id).ToArray();
            ViewBag.idClient = listTimesheet.Select(a => a.idClient).ToArray();

            return View(listTimesheet);
        }

        public ActionResult Send(string kirim, string lewati, string Email) 
        { 
            List<long> id = (List<long>)Session["Id"];
            List<long> idClient = (List<long>)Session["IdClient"];
            ViewBag.getMonth = SubmissionRepo.ListMonth();
            
            string[] result = new string[id.Count];
            string[] resultE = new string[idClient.Count];
            bool value = true;
            List<SelectListItem> emailList = new List<SelectListItem>();

            string j = " ";

            //if (month != null)
            //{
            //    for (int i = 0; i < 12; i++)
            //    {
            //        if (month == ViewBag.getMonth[i].value)
            //        {
            //            j = ViewBag.getMonth[i].text;

            //            break;
            //        }
            //    }
            //}
            //data[1].value = year;
            //data[1].text = year;

            var monthText = j;

            for (int i = 0; i < id.Count(); i++)
            {
                var temp = id[i];
                var tempClient = idClient[i];
                var email = SubmissionRepo.getDataClientById(tempClient);

                result[i] = SubmissionRepo.setSend(temp);
                emailList.Insert(i, new SelectListItem { Text = email.user_email, Value = email.id.ToString() });

                if (result[i] != "ok")
                {
                    value = false;
                }
            }

            //for (int i = 0; i < idClient.Count(); i++)
            //{
            //    var temp = idClient[i];
            //    resultE[i] = SubmissionRepo.sendClient(temp, year, monthText);
            //    if (result[i] != "ok")
            //    {
            //        value = false;
            //    }
            //}
            if (!string.IsNullOrEmpty(kirim) && string.IsNullOrEmpty(lewati))
            {
                MailMessage mail = new MailMessage();
                String[] emailcc = Email.Split(';');
                String subject = "Review Timesheet";
                String body = @"<html>
                      <body>
                      <p>Dear All, </p>
                      <p>Please check timesheet submission to approve or reject</p>
                      <p>Thank you</p> </body> </html>";
                String password = "amiichda";
                SmtpClient client = new SmtpClient();
                mail.From = new MailAddress("hayatiichda35@gmail.com");
                emailList = emailList.OrderByDescending(t => t.Value).ToList();
                String emailUser = emailList[0].Text;
                mail.To.Add(new MailAddress(emailUser));
                for (int x = 1; x < emailList.Count; x++)
                {
                    if (emailUser != emailList[x].Text)
                    {
                        mail.To.Add(new MailAddress(emailList[x].Text));
                    }
                }
                foreach (String mailcc in emailcc)
                {
                    mail.To.Add(new MailAddress(mailcc));
                };
                mail.Subject = subject;
                mail.IsBodyHtml = true;
                mail.Body = body;
                client.Host = "smtp.gmail.com";
                client.Port = 587;
                client.EnableSsl = true;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(mail.From.ToString(), password);
                client.Send(mail);
            }

            if (!string.IsNullOrEmpty(lewati) && string.IsNullOrEmpty(kirim))
            {
                MailMessage mail = new MailMessage();
                String subject = "Review Timesheet";
                String body = @"<html>
                      <body>
                      <p>Dear All, </p>
                      <p>Please check timesheet submission to approve or reject</p>
                      <p>Thank you</p> </body> </html>";
                String password = "amiichda";
                SmtpClient client = new SmtpClient();
                mail.From = new MailAddress("hayatiichda35@gmail.com");
                emailList = emailList.OrderByDescending(t => t.Value).ToList();
                String emailUser = emailList[0].Text;
                mail.To.Add(new MailAddress(emailUser));
                for (int x = 1; x < emailList.Count; x++)
                {
                    if (emailUser != emailList[x].Text)
                    {
                        mail.To.Add(new MailAddress(emailList[x].Text));
                    }
                }
                mail.Subject = subject;
                mail.IsBodyHtml = true;
                mail.Body = body;
                client.Host = "smtp.gmail.com";
                client.Port = 587;
                client.EnableSsl = true;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(mail.From.ToString(), password);
                client.Send(mail);
            }
            if (value == true)
            {
                return Json(new { message = "berhasil" }, JsonRequestBehavior.AllowGet);
                
            }
            else
            {
                return Json(new { message = "gagal" }, JsonRequestBehavior.AllowGet);
            }
            Session["Id"] = null;
            Session["IdClient"] = null;
        }
    }
}

MiniProject228/Views/TimesheetSubmission/_EmailCC.cshtml
@using (Html.BeginForm("Send", "TimesheetSubmission", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{

    <div class="row">
        <div class="col-md-8" style="margin-left:5%;">
            <label>Gunakan Sebagai divider</label><br />
            @Html.Editor("Email", new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-lg-10">
            <div class="col-md-offset-8 col-md-10">
                <input type="submit" value="lewati" name="lewati" class="btn btn-primary" id="btn-lewati" />
                <input type="submit" value="kirim" name="kirim" class="btn btn-warning" id="btn-kirim"/>
            </div>        </div>
    </div>

}

MiniProject228/Views/TimesheetSubmission/_List.cshtml
@model IEnumerable<ViewModel.TimesheetViewModal>

<style>
    #responsibility, .form-control {
        max-width: 1000px;
    }
</style>


<div class="panel-group">
    <div class="tab-content">
        <div class="row" style="background-color:#337ab7">
            <h4 style="color: white; margin-left: 20px">Timesheet Submission</h4>
        </div>
        <br />

        <div class="form-group" style="max-width:1000px;">
            <div class="row">
                <div class="col-sm-6">
                    <label>Tahun*</label>
                    @Html.DropDownList("tsaYear", new SelectList(ViewBag.getYear, "value", "text"), "Pilih Tahun", new { @class = "form-control", @thisMonth = ViewBag.thisMonth })
                </div>
                <div class="col-sm-6">
                    <label>Bulan*</label>
                    @Html.DropDownList("tsaMonth", new SelectList(ViewBag.getMonth, "value", "text"), "Pilih Bulan", new { @class = "form-control", @thisYear = ViewBag.thisYear, @savedMonth = ViewBag.savedMonth })
                </div>
            </div>
        </div>

        <div class="row" style="margin-top:8px; margin-bottom:8px; margin-right:5px;" id="id-hide-me">
            <div class="col-3"></div>
            <div class="col-md-offset-8 col-3">
                <div class="btn-group">
                    <button type="button" class="btn" style="background-color:darkgray; width:140px" data-dismiss="modal" disabled><a style="color:white; font-weight:bold">Reset</a></button>
                    <button type="submit" class="btn" style="background-color:darkgray; width:140px" disabled><a style="color:white; font-weight:bold">Submit</a></button>
                </div>
            </div>
        </div>

        <div class="col-md-12" style="margin-top:8px; display:none;" id="id-show-me">

        </div>
    </div>
</div>

<script>

    $("#tsaMonth").bind('change', function (event) {

        var i = $('#tsaMonth').val();
        var tahun = $('#tsaYear').val();
        var monthVal = $("#tsaMonth option:selected").val();
        var monthText = $("#tsaMonth option:selected").text();

        if (tahun == "" || tahun == null) {
            alert("Isi Tahun");
            $('option:selected', this).removeAttr('selected');
        } else if (monthVal == "" || monthVal == null) {
            alert("Bulan tidak boleh kosong");
        } else {
            if (i != null) {
                $.ajax({
                    url: '/TimesheetSubmission/listTimesheetView',
                    method: 'get',
                    data: { year: tahun, month: i },
                    success: function (response) {
                        $("#id-show-me").html(response);
                        $("#id-hide-me").hide();
                        $("#id-show-me").show();
                    }
                })
            }
            else if (i == null) {
                $("#id-show-me").hide();
            }
        }
    })

    $("#tsaYear").bind('change', function (event) {
        var yearVal = $("#tsaYear option:selected").val();
        var yearText = $("#tsaYear option:selected").text();
        var monthVal = $("#tsaMonth option:selected").val();
        var monthText = $("#tsaMonth option:selected").text();

        if (monthText == "Pilih Bulan" || yearVal == null || yearVal == "" || monthVal == null) {
        } else {
            $.ajax({
                url: '/TimesheetSubmission/listTimesheetView',
                method: 'get',
                data: { year: yearVal, month: monthVal },
                success: function (response) {
                    $("#id-show-me").html(response);
                    $("#id-hide-me").hide();
                    $("#id-show-me").show();
                }
            })
        }
    })

</script>

MiniProject228/Views/TimesheetSubmission/listTimesheetView.cshtml
@model IEnumerable<ViewModel.TimesheetViewModal>

@{
    Layout = null;
}

<style>
    table {
        font-family: Aria
            l, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        text-align: left;
        padding: 15px;
    }

    td {
        text-align: left;
        padding: 15px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<div class="col-12">
    <table class="table">
        <tr>
            <th>
                STATUS
            </th>
            <th>
                TANGGAL
            </th>
            <th>
                CLIENT
            </th>
            <th>
                NAMA PEGAWAI
            </th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @item.timesheet_date.ToString("MMMM dd, yyyy")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.namaPG)
        </td>
    </tr>
        }

    </table>

    <div class="row" style="margin-top:8px; margin-bottom:8px; margin-right:5px;" id="id-hide-me">
        <div class="col-3"></div>
        <div class="col-md-offset-8 col-3">
            <div class="btn-group">
                <button type="button" id="btn-reset" style="background-color:orangered; width:140px" data-dismiss="modal"><a style="color:white; font-weight:bold">Reset</a></button>
                <button type="submit" id="btn-send" style="background-color:#337ab7; width:140px"><a style="color:white; font-weight:bold">Submit</a></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEmail" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary header-modal-sm">
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body modal-create">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<script>
    $("#btn-reset").click(function () {
        GetList();
    })



    $("#btn-send").click(function () {
        var y = $('#tsaYear').val();
        var m = $('#tsaMonth').val();
        var idSend  = @Html.Raw(Json.Encode(@ViewBag.idSend));
        var idPekerja  = @Html.Raw(Json.Encode(@ViewBag.idClient));
        if (y == null || y == "") {
            $("#tsaYear").after("<p>Please select Year</p>")
        } else if (m == null || m == "") {
            $("#tsaMonth").after("<p>Please select Month</p>")
        } else {
            $.ajax({
                url: '/TimesheetSubmission/EmailCC',
                method: 'post',
                data: { id: idSend, idClient: idPekerja, year: y, month: m },
                success: function (response) {
                    $(".header-modal-sm").css("background-color", "#337ab7");
                    $(".modal-title").html("Tambah Email Penerima");
                    $(".modal-create").html(response);
                    $("#modalEmail").modal("show");
                    //alert("Berhasil");
                    //window.location.reload();
                }
            })
        }
    })

</script>